# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ProdGenerateInspireAfterCreatedLastAndNoti

on:
  schedule:
  - cron: '0 0,3,6,9 * * *'
  # KST 9시부터 3시간 간격으로 실행, 19시를 마지막으로 실행
  workflow_dispatch:

jobs:
  gen:
    environment: PROD
    env:
      INSPIRE_SERVER: ${{ secrets.INSPIRE_SERVER }}
      TYPE : inspire
      TIMESTAMP_AFTER : 259200
      CONTEXT_LOCAL : '10자에서 50자 사이로 내 감정과 상태에 도움이 되는 말을 한국어로 해줘. 상담의 형태로 답변해주 는데, 직접적으로 상담이라고 언급하지는 말아줘.  문법에 맞는 문장을 사용하고 특수문자나 욕설은 사용하지 말아주세요. 최대 50자를 넘지 말아주세요.'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Gen
      run: cd inspire && ./app

  sleep:
    needs: gen
    runs-on: ubuntu-latest
    steps:
    - name: Sleep
      run: sleep 60

  noti:
    needs: sleep
    environment: PROD
    env:
      INSPIRE_SERVER: ${{ secrets.INSPIRE_SERVER }}
      TYPE : notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Noti
      run: cd inspire && ./app
